version: "3.4"

## This overrides frontend on the docker-compose.yml file when running run.local.sh, this is done so the frontend local container
## can be updated in real time while editing frontend code, it only needs to be restarted when changing the env variables
services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  nginx:
    image: nginx:1.25.1-alpine
    container_name: nginx
    restart: always
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    environment:
      - NGINX_ENV=${NGINX_ENV}
      - NGINX_SCHEME=${NGINX_SCHEME:-https}
      - NGINX_SERVER_PORT=${NGINX_SERVER_PORT:-443}
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d/
      - NGINX_FRONTEND_DOMAIN_NAME=${NGINX_FRONTEND_DOMAIN_NAME}
      - NGINX_BACKEND_DOMAIN_NAME=${NGINX_BACKEND_DOMAIN_NAME}
      - NGINX_KEYCLOAK_DOMAIN_NAME=${NGINX_KEYCLOAK_DOMAIN_NAME}
      - NGINX_MINIO_DOMAIN_NAME=${NGINX_MINIO_DOMAIN_NAME}
      - NGINX_CONSOLE_MINIO_DOMAIN_NAME=${NGINX_CONSOLE_MINIO_DOMAIN_NAME}
      - NGINX_SUPERSET_DOMAIN_NAME=${NGINX_SUPERSET_DOMAIN_NAME}
      - NGINX_SUPERSET_GUEST_DOMAIN_NAME=${NGINX_SUPERSET_GUEST_DOMAIN_NAME}
      - NGINX_AIRFLOW_DOMAIN_NAME=${NGINX_AIRFLOW_DOMAIN_NAME}
      - NGINX_HOP_DOMAIN_NAME=${NGINX_HOP_DOMAIN_NAME}
      - NGINX_DRUID_DOMAIN_NAME=${NGINX_DRUID_DOMAIN_NAME}
      - NGINX_DRUID_COORDINATOR_DOMAIN_NAME=${NGINX_DRUID_COORDINATOR_DOMAIN_NAME}
      - NGINX_FREELLMAPI_CONSOLE_DOMAIN_NAME=${NGINX_FREELLMAPI_CONSOLE_DOMAIN_NAME}
      - NGINX_FREELLMAPI_SERVER_DOMAIN_NAME=${NGINX_FREELLMAPI_SERVER_DOMAIN_NAME}
      - NGINX_UPSTREAM_FRONTEND=${NGINX_UPSTREAM_FRONTEND}
      - NGINX_UPSTREAM_BACKEND=${NGINX_UPSTREAM_BACKEND}
      - NGINX_UPSTREAM_AIRFLOW=${NGINX_UPSTREAM_AIRFLOW}
      - NGINX_UPSTREAM_KEYCLOAK=${NGINX_UPSTREAM_KEYCLOAK}
      - NGINX_UPSTREAM_MINIO=${NGINX_UPSTREAM_MINIO}
      - NGINX_UPSTREAM_SUPERSET=${NGINX_UPSTREAM_SUPERSET}
      - NGINX_UPSTREAM_HOP=${NGINX_UPSTREAM_HOP}
      - NGINX_UPSTREAM_DRUID=${NGINX_UPSTREAM_DRUID}
      - NGINX_UPSTREAM_DRUID_COORDINATOR=${NGINX_UPSTREAM_DRUID_COORDINATOR}
      - NGINX_UPSTREAM_FREELLMAPI_CONSOLE=${NGINX_UPSTREAM_FREELLMAPI_CONSOLE}
      - NGINX_UPSTREAM_FREELLMAPI_SERVER=${NGINX_UPSTREAM_FREELLMAPI_SERVER}
      - AIRFLOW__WEBSERVER__SESSION_LIFETIME_MINUTES=${AIRFLOW__WEBSERVER__SESSION_LIFETIME_MINUTES}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/package-conf/:/etc/nginx/templates/package-conf/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - airflow-webserver
      - backend
      - storage
      - coordinator
      - router
      - hop
      - frontend
      - keycloak
      - superset

