# Generated by Django 4.2.1 on 2023-05-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('file_name', models.CharField(max_length=100, verbose_name='File Name')),
                ('file_type', models.CharField(max_length=20, verbose_name='File Type')),
                ('file_url', models.CharField(max_length=20, verbose_name='File URL')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
            ],
        ),
    ]
