# Generated by Django 4.2.1 on 2023-05-23 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='file_url',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='data/%Y/%m/%d', verbose_name='File'),
            preserve_default=False,
        ),
    ]
