# Generated by Django 4.2.1 on 2023-05-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_fileupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='File Type'),
        ),
    ]
