# Generated by Django 4.2.1 on 2023-05-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_fileupload_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(max_length=100000, upload_to='data/%Y/%m/%d/', verbose_name='File'),
        ),
    ]
